import os
import random
import json
import pickle
import pandas as pd
import torch
import numpy as np
import pyvips
from math import log2
from torch.utils.data import Dataset

class HisPathDataset(Dataset):
    """Dataset for histopathology patches.

    Expected directory layout (Option A – recommended)::

        <project_root>/
        ├─ data/
        │   ├─ tif/          # multi‑page TIFFs generated by save2tif
        │   ├─ mask/         # binary/multi‑class masks from MaskTrans
        │   ├─ roi/          # optional ROI TIFFs from MaskTrans
        │   └─ pkl/          # feather patch index dictionaries from filtering_to_pkl
        └─ cfg/
            └─ fold_h.json   # case list generated by gen_datalistyk6g4

    The class now accepts explicit path arguments with sensible defaults so that
    the dataset works out‑of‑the‑box after running the wsi_tool pipeline.
    """

    def __init__(self,
                 stage: str = "train_label",
                 transform=None,
                 dataroot: str = None,
                 datalist: str = None,
                 classes: list = None,
                 patchsize: int = 256,
                 stridesize: int = 128,
                 tifpage: int = 0,
                 lr_ratio: int = 8,
                 preprocess=None):
        super().__init__()

        # ---------------------------- 路徑設定 ----------------------------
        self.data_root = dataroot
        self.list_path = datalist

        # -------------------------- 超參數保存 -------------------------
        self.transform = transform
        self.classes = classes or []
        self.patchsize = patchsize
        self.stridesize = stridesize
        self.tifpage = tifpage
        self.lrratio = lr_ratio
        self.preprocess = preprocess

        # 其他標誌
        self.stage = stage
        self.istrain = True if "train" in stage else False
        self.islabel = False if stage == "train_unlabel" else True

        # --------------------------- 讀取資料 -------------------------
        totaldict = self._loading_data(self.data_root, self.list_path, self.stage, self.islabel)
        self.datalist = self._select_data(totaldict, self.stage)

        # 低解析度輔助參數
        self.lrshift = self.patchsize // 2 - self.patchsize // self.lrratio // 2
        self.lrdiff = int(log2(lr_ratio))

    # -----------------------------------------------------------------
    # 基本 Dataset 介面
    # -----------------------------------------------------------------
    def __len__(self):
        return len(self.datalist)

    # ---------------------------------------------------------------
    # 讀取 case list (JSON)
    # ---------------------------------------------------------------
    def readDataList(self, stage: str, datalist: str = None):
        with open(datalist) as fp:
            dataset = json.load(fp)

        case = []
        if stage == "train_label" and "label" in dataset.get("train", {}):
            case += dataset["train"]["label"]
        elif stage == "train_unlabel" and "unlabel" in dataset.get("train", {}):
            case += dataset["train"]["unlabel"]
        elif stage in ("valid", "test"):
            case += dataset.get(stage, {}).get("label", [])
        print(f"{stage} with {len(case)} cases.")
        return case

    # ---------------------------------------------------------------
    # 讀取 .feather 檔案
    # ---------------------------------------------------------------
    def _loading_data(self, data_root, datalist_path, stage, islabel):
        cases = self.readDataList(stage, datalist_path)
        # 根據是否為標註集決定要讀取 feather 裡的哪一個 subset
        target_set = 'label' if islabel else 'unlabel'
        
        totaldict = {}
        for case in cases:

            feather_file = os.path.join(data_root, case['org'], case['pkl_root'], f"{case['filename']}.feather")
            if not os.path.exists(feather_file):
                continue
            try:
                df = pd.read_feather(feather_file)
                # 篩選對應的資料集
                df = df[df['set'] == target_set]
                for cat, group in df.groupby('category'):
                    if cat not in totaldict:
                        totaldict[cat] = []
                    # 將 feather 的資料轉換為原有的 List 格式: [name, [x, y]]
                    for _, row in group.iterrows():
                        if islabel:
                            totaldict[cat].append([os.path.join(data_root, case['org'], case['img_root'], f"{case['filename']}{case['ext']}"),    #img path
                                                   os.path.join(data_root, case['org'], case['mask_root'], f"{case['filename']}{case['ext']}"),   #mask path
                                                   row['label'],
                                                   row['coordinates'].tolist() if isinstance(row['coordinates'], np.ndarray) else row['coordinates'],
                                                   case['ext']])
                        else:
                            totaldict[cat].append([os.path.join(data_root, case['org'], case['img_root'], f"{case['filename']}{case['ext']}"),     #img path
                                                   None,
                                                   row['label'],
                                                   row['coordinates'].tolist() if isinstance(row['coordinates'], np.ndarray) else row['coordinates'],
                                                   case['ext']])

            except Exception as e:
                print(f"Error loading {case}.feather: {e}")
                continue
                
        print(f'---data amount of different type patches ({target_set}) ---')
        for k, v in totaldict.items():
            print(k, ':', len(v))
        return totaldict

    # ---------------------------------------------------------------
    # 依比例抽樣 (還原回原本的流程，並支援新標籤)
    # ---------------------------------------------------------------
    def _select_data(self, pkldict, stage):
        # 根據 filtering_to_pkl 輸出的類別來定義
        label_keys = ['partial_label_heavy', 'partial_label_light', 'tissue_labeled_heavy', 'tissue_labeled_light','tissue_background', 'partial_background']
        unlabel_keys = ['tissue_background', 'partial_background']
        
        # 手動控制各類別的抽樣上下限 [最低抽樣數, 最高抽樣數]
        # (預設皆設定為 [0, 5000]，可依照需求手動調整)

        ratio = {
            'tissue_background': 1,
            'partial_background': 1,
            'partial_label_heavy': 1,
            'partial_label_light': 1,
            'tissue_labeled_heavy': 1,
            'tissue_labeled_light': 1,
        }

        # limit = {
        #     'tissue_background': [0, 500] if stage == "train_unlabel" else [0, 100],
        #     'partial_background': [0, 500] if stage == "train_unlabel" else [0, 100],
        #     'partial_label_heavy': [0, 500],
        #     'partial_label_light': [0, 250],
        #     'tissue_labeled_heavy': [0, 500],
        #     'tissue_labeled_light': [0, 250],
        # }
        limit = {
            'tissue_background': [0, 5000] if stage == "train_unlabel" else [0, 1000],
            'partial_background': [0, 5000] if stage == "train_unlabel" else [0, 1000],
            'partial_label_heavy': [0, 5000],
            'partial_label_light': [0, 2500],
            'tissue_labeled_heavy': [0, 5000],
            'tissue_labeled_light': [0, 2500],
        }
        
        datalist = []

        if self.islabel: 
            # Label set 的處理流程 
            for k in label_keys:
                if k not in pkldict: continue
                r = ratio.get(k, 0)
                sample_num = int(len(pkldict[k]) * r)
                if sample_num > limit[k][1]:
                    sample_num = limit[k][1]
                elif sample_num <= 0:
                    sample_num = 0
                sample_datas = random.sample(pkldict[k], sample_num)    
                print(f'real labeled input data {k} : {len(sample_datas)}')
                datalist += sample_datas

        else: 
            # Unlabel set 的處理流程 
            for k in unlabel_keys:
                if k not in pkldict: continue
                r = ratio.get(k, 0)
                sample_num = int(len(pkldict[k]) * r)
                if sample_num > limit[k][1]:
                    sample_num = limit[k][1]
                elif sample_num <= 0:
                    sample_num = 0
                sample_datas = random.sample(pkldict[k], sample_num)    
                print(f'real unlabeled input data {k} : {len(sample_datas)}')
                datalist += sample_datas

        for _ in range(10):
            np.random.shuffle(datalist)
        return datalist

    # ---------------------------------------------------------------
    # 讀取 WSI（tif / svs / ndpi / mrxs）
    # ---------------------------------------------------------------
    def read_WSI(self, wsi_path, data_type, level):
        data_type = data_type[1:] if data_type.startswith('.') else data_type
        # return pyvips.Image.openslideload(wsi_path, level=level)
        if data_type == 'tif':
            return pyvips.Image.tiffload(wsi_path, page=level)
        elif data_type in ['svs','ndpi','mrxs']:
            return pyvips.Image.new_from_file(wsi_path, level=level)
        else:
            print('type not include')
            return None

    # ---------------------------------------------------------------
    # 裁切與校正
    # ---------------------------------------------------------------
    def _tiffcrop(self, slide, x, y, width, height):
        region = pyvips.Region.new(slide)
        vi = region.fetch(x, y, width, height)
        image = np.ndarray(buffer=vi, dtype=np.uint8, shape=[height, width, slide.bands])
        if image.shape[2] == 4:
            image = image[:, :, 0:3]
        return image

    def _tiffcheckcrop(self, slide, x, y, width, height):
        maxwidth, maxheight = slide.width, slide.height
        maxwidth -= x
        maxheight -= y
        if x >= 0 and y >= 0 and width <= maxwidth and height <= maxheight:
            return self._tiffcrop(slide, x, y, width, height)
        else:
            w_comp = -x if x < 0 else 0
            h_comp = -y if y < 0 else 0
            w_crop = np.clip(width-w_comp, None, maxwidth)  
            h_crop = np.clip(height-h_comp, None, maxheight)
            crop = self._tiffcrop(slide, np.clip(x, 0, None), np.clip(y, 0, None), w_crop, h_crop)

            image = np.full((height, width, 3), 255, dtype=np.uint8) if crop.shape[2] == 3 else np.zeros((height, width, 1))
            image[h_comp:h_comp+h_crop, w_comp:w_comp+w_crop] = crop
            return image

    # ---------------------------------------------------------------
    # 取得單筆資料
    # ---------------------------------------------------------------
    def __getitem__(self, idx):
        dataitem = self.datalist[idx]
        img_path, mask_path, name, (x, y), datatype = dataitem

        tifpath = os.path.join(img_path)
        slide = self.read_WSI(tifpath, datatype, level=self.tifpage)

        if self.istrain:
            x += random.randint(0, self.stridesize)
            y += random.randint(0, self.stridesize)
            if (x + self.patchsize) > slide.width:
                x = slide.width - self.patchsize
            if (y + self.patchsize) > slide.height:
                y = slide.height - self.patchsize

        image = self._tiffcrop(slide, x, y, self.patchsize, self.patchsize)

        slide2 = self.read_WSI(tifpath, datatype, level=self.tifpage)
        lrimage = self._tiffcheckcrop(
            slide2, 
            x // self.lrratio - self.lrshift, 
            y // self.lrratio - self.lrshift, 
            self.patchsize, self.patchsize)

        if self.islabel:
            slide_mask = self.read_WSI(mask_path, 'tif', level=self.tifpage)
            mask = self._tiffcrop(slide_mask, x, y, self.patchsize, self.patchsize)

            if self.transform:
                sample = self.transform(image=image, mask=mask, lrimage=lrimage)
                image, mask, lrimage = sample['image'], sample['mask'], sample['lrimage']
            if self.preprocess:
                sample = self.preprocess(image=image, mask=mask, lrimage=lrimage)
                image, mask, lrimage = sample['image'], sample['mask'], sample['lrimage']
            mask = torch.squeeze(mask, dim=0).long()
            return image, mask, lrimage

        else:
            if self.transform:
                sample = self.transform(image=image, lrimage=lrimage)
                image, lrimage = sample['image'], sample['lrimage']
            if self.preprocess:
                sample = self.preprocess(image=image, lrimage=lrimage)
                image, lrimage = sample['image'], sample['lrimage']
            return image, lrimage
